### ISSUE TITLE
Always using src/scss

### ISSUE THREAD

**Issue by ryepesg** [aew/lein-sassc#1]
I'm trying to configure sassc to work with resources/scss instead of src/scss, but it keeps using the old directory:

  :plugins [...
            [lein-sassy "1.0.7"]
            [lein-sassc "0.10.4"]]
   :sassc
   {:src "resources/scss/main.scss"
    :output-to "resources/public/css/main.scss"
    :style "nested"
    :import-path "resources/scss"} 
   :sass {:src "resources/sass/stylesheets" :dst "resources/public/css"} 
  :hooks [leiningen.sassc]

lein compile
Compile SASS/SCSS files.
sassc -t nested -I src/scss resources/scss/main.scss target/sassc/main.css

sassc -t nested -I src/scss src/scss/main.scss resources/public/css/main.css
Error: File to read not found or unreadable: src/scss/main.scss

sassc -t nested -I src/scss src/scss/main.scss target/sassc/main.css
Error: File to read not found or unreadable: src/scss/main.scss

sassc -t nested -I resources/scss src/scss/main.scss target/sassc/main.css
Error: File to read not found or unreadable: src/scss/main.scss

**Comment by KevinGreene** [comment]
The issue is that you are using a map, not an array, for the value of `sassc`.

```
:sassc
[{:src "resources/scss/main.scss"
:output-to "resources/public/css/main.scss"
:style "nested"
:import-path "resources/scss"}]
```

That should run correctly. Based on the fact that you have both sassy and sassc, I think you are using luminus, in which case this is being fixed in that project as well.

**Comment by ryepesg** [comment]
That's correct, I im using Luminus, glad to know it will be fixed, thanks.
